# Generated by Django 3.0.5 on 2020-05-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_question_result_student_teacher_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='how', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='How', max_length=50),
        ),
    ]
