# Generated by Django 3.0.5 on 2020-05-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200523_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='no_subject',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.AddField(
            model_name='test',
            name='class_name',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='test',
            name='password',
            field=models.CharField(default='init', max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='section',
            field=models.CharField(default='D', max_length=1),
        ),
    ]
