# Generated by Django 3.0.5 on 2020-05-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200524_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.TextField(default='A'),
        ),
    ]
