# Generated by Django 3.0.5 on 2020-05-28 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_question_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='section',
        ),
    ]
