# Generated by Django 3.0.5 on 2020-06-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_test_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='subject',
            field=models.CharField(default='Maths', max_length=80),
        ),
    ]
